# Generated by Django 2.1.2 on 2018-12-21 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='begin_selected',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 9, 29, 225437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='end_modify',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 9, 29, 225503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='end_selected',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 9, 29, 225474, tzinfo=utc)),
        ),
    ]
