# Generated by Django 2.1.2 on 2018-12-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181207_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='rel_SCtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SCtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='uuid',
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Courses'),
        ),
        migrations.AddField(
            model_name='sctable',
            name='classobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classes'),
        ),
        migrations.AddField(
            model_name='sctable',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rel_SCtable'),
        ),
        migrations.AddField(
            model_name='sctable',
            name='studentobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
    ]
