# Generated by Django 2.1.2 on 2018-12-21 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181221_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='begin_selected',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 14, 56, 10, 8790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='end_modify',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 14, 56, 10, 8894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='end_selected',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 14, 56, 10, 8850, tzinfo=utc)),
        ),
    ]
