# Generated by Django 2.1.2 on 2018-12-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_classes_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='app.Courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Departments')),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='app.Courses')),
            ],
        ),
    ]
